# Generated by Django 5.2.6 on 2025-11-11 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='calificaciontributaria',
            options={'ordering': ['calificacion', 'secuencia_evento']},
        ),
        migrations.RemoveIndex(
            model_name='calificaciontributaria',
            name='api_calific_anio_098d71_idx',
        ),
        migrations.RemoveIndex(
            model_name='calificaciontributaria',
            name='api_calific_secuenc_74d4bf_idx',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_documento',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT / Documento'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archivo'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_emision',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_pago',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.instrumento'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='mercado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mercado'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='monto_factor',
            field=models.DecimalField(db_index=True, decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='anio',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributarias', to='api.calificacion'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='evento_capital',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='ingreso_por_montos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='secuencia_evento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
