# Generated by Django 5.2.6 on 2025-11-12 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo', models.CharField(help_text='Nombre del archivo de respaldo (ej. backup.sql.gz)', max_length=255)),
                ('estado', models.CharField(choices=[('Completo', 'Completo'), ('Interrumpido', 'Interrumpido'), ('Con Error', 'Con Error')], default='Completo', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el respaldo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
