# Generated by Django 5.2.7 on 2025-11-05 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_emision',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_pago',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='monto_factor',
            field=models.DecimalField(db_index=True, decimal_places=4, max_digits=18),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fecha_emision', 'estado'], name='api_calific_fecha_e_fae286_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['usuario', 'fecha_registro'], name='api_calific_usuario_bc0c87_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['instrumento', 'mercado'], name='api_calific_instrum_28b206_idx'),
        ),
    ]
