# Generated by Django 5.2.6 on 2025-11-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
