# Generated by Django 5.2.7 on 2025-11-05 00:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_calificacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='calificaciontributaria',
            options={'ordering': ['calificacion', 'secuencia_evento'], 'verbose_name': 'Calificación Tributaria', 'verbose_name_plural': 'Calificaciones Tributarias'},
        ),
        migrations.RemoveIndex(
            model_name='calificacion',
            name='api_calific_usuario_bc0c87_idx',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archivo', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_emision',
            field=models.DateField(db_index=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_pago',
            field=models.DateField(db_index=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='mercado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mercado', verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='monto_factor',
            field=models.DecimalField(db_index=True, decimal_places=4, max_digits=18, verbose_name='Monto Factor'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='anio',
            field=models.IntegerField(db_index=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributarias', to='api.calificacion', verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='evento_capital',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Evento Capital'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='ingreso_por_montos',
            field=models.BooleanField(default=False, verbose_name='Ingreso por Montos'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='secuencia_evento',
            field=models.IntegerField(help_text='Número que indica el orden del evento', verbose_name='Secuencia del Evento'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor Histórico'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['usuario', 'created_at'], name='api_calific_usuario_d260f8_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['anio', 'calificacion'], name='api_calific_anio_098d71_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['secuencia_evento'], name='api_calific_secuenc_74d4bf_idx'),
        ),
    ]
