# Generated by Django 5.2.6 on 2025-12-11 02:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auditoria_calificacion_auditoria_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='ruta',
            field=models.FileField(blank=True, upload_to='cargas/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.instrumento'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='mercado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mercado'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='anio',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
